# Documentation
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Production Build

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

# on: [push]
on:
  push:
    branches:
      - main
      - "releases/**"

env:
  SERVER: production

# permissions:
#   actions: read|write|none
#   checks: read|write|none
#   contents: read|write|none
#   deployments: read|write|none
#   id-token: read|write|none
#   issues: read|write|none
#   discussions: read|write|none
#   packages: read|write|none
#   pages: read|write|none
#   pull-requests: read|write|none
#   repository-projects: read|write|none
#   security-events: read|write|none
#   statuses: read|write|none
# permissions: read-all|write-all

jobs:
  build:
    name: Production Build of Website
    runs-on: ubuntu-latest

    steps:
      - name: Environmental variables
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      #  https://github.com/actions/cache/blob/main/examples.md#node---npm
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm i

      - name: Build Project
        run: npm run build
